trigger:
  branches:
    include:
      - main  # Trigger on changes to the 'main' branch

pr:
  branches:
    include:
      - main  # Trigger on PRs to the 'main' branch

pool:
  name: Default  # Use your self-hosted agent pool name

variables:
  rgname: 'azure-patroni-integration-rg'  # Replace with your resource group name
  location: 'Australia East'  # Define location here for reusability
  azureSubscription: 'AzureResumeConnection'  # Replace with your service connection name

jobs:
  - job: DeployInfrastructure
    displayName: 'Deploy Infrastructure with Bicep'
    steps:
      - checkout: self

      # Step 1: Install Bicep CLI
      - task: UseDotNet@2
        displayName: 'Install Bicep CLI'
        inputs:
          packageType: 'sdk'
          version: '6.x'  # Ensure the latest version compatible with Bicep is installed
          installationPath: $(Agent.ToolsDirectory)/dotnet

      - script: |
          echo "Installing Bicep CLI..."
          az bicep install
        displayName: 'Install Bicep CLI'

      # Step 2: Verify File Paths
      - script: |
          echo "Verifying file paths..."
          if exist "$(Build.SourcesDirectory)\infrastructure\main.bicep" (
            echo "main.bicep found."
          ) else (
            echo "main.bicep not found."
            exit /b 1
          )
          if exist "$(Build.SourcesDirectory)\infrastructure\parameters.json" (
            echo "parameters.json found."
          ) else (
            echo "parameters.json not found."
            exit /b 1
          )
        displayName: 'Verify File Paths'

      # Step 3: Deploy Bicep file
      - task: AzureCLI@2
        inputs:
          azureSubscription: $(azureSubscription)
          scriptType: powershell
          scriptLocation: inlineScript
          inlineScript: |
            echo "Deploying Bicep file..."
            az deployment group create --resource-group $(rgname) --template-file $(Build.SourcesDirectory)/infrastructure/main.bicep --parameters @$(Build.SourcesDirectory)/infrastructure/parameters.json
        displayName: 'Deploy Bicep File'

      # Step 4: Azure Logout
      - task: AzureCLI@2
        displayName: 'Azure Logout'
        inputs:
          azureSubscription: $(azureSubscription)
          scriptType: powershell
          scriptLocation: inlineScript
          inlineScript: |
            az logout